name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}
        id: setup_ssh

      - name: Test SSH connection
        run: |
          ssh -T git@github.com || echo "SSH authentication to GitHub successful, but no shell access"

      - name: Add host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Frontend
        run: |
          SERVER_IP="${{ secrets.SERVER_IP }}"
          USER_NAME_SERVER="${{ secrets.USER_NAME_SERVER }}"
          PROJECT_DIR="/home/mutu/project-frontend/thy-fly-menu-helper"  # Ensure this is a valid path

          # Debugging: Print PROJECT_DIR to check if it's set correctly
          echo "PROJECT_DIR: $PROJECT_DIR"

          # Check if PROJECT_DIR is not empty
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: PROJECT_DIR is empty or not set. Please check the value."
            exit 1
          fi

          ssh -T $USER_NAME_SERVER@$SERVER_IP << EOF
            set -e

            # Debugging: Print the PROJECT_DIR on the server to verify it
            echo "PROJECT_DIR on server: $PROJECT_DIR"

            # Check if PM2 is installed, install it if not
            if ! command -v pm2 &> /dev/null
            then
              echo "PM2 not found. Installing PM2..."
              sudo npm install -g pm2
            else
              echo "PM2 is already installed."
            fi

            # Stop the running application (if it exists)
            echo "Checking if the application is running..."
            if pm2 list | grep -q "thyflightmenujs-app"; then
              echo "Application is running. Stopping it..."
              pm2 stop thyflightmenujs-app
            else
              echo "Application is not running. Proceeding..."
            fi

            # Ensure the directory path is correctly passed and exists
            echo "Checking if project directory exists..."
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Creating project directory..."
              mkdir -p "$PROJECT_DIR"  # Create the project directory if it doesn't exist
              echo "Cloning repository..."
              git clone git@github.com:MuratTunc/thy-fly-menu-helper.git "$PROJECT_DIR"
            else
              echo "Project directory exists. Pulling latest changes..."
              cd "$PROJECT_DIR"
              git reset --hard
              git pull origin main
            fi

            # Navigate to the project directory
            cd "$PROJECT_DIR"

            # Install dependencies
            echo "Installing dependencies..."
            npm install

            # Build the project
            echo "Building the project..."
            npm run build

            # Start or reload the application with PM2
            echo "Starting the application with PM2..."
            pm2 start npm --name "thyflightmenujs-app" -- start || pm2 restart "thyflightmenujs-app"
            pm2 save

            # Confirm PM2 status
            echo "Checking PM2 status..."
            pm2 status || { echo "PM2 process failed to start! Please check the logs."; exit 1; }

            echo "Deployment complete!"
          EOF
